### ISSUE TITLE
Repository is huge

### ISSUE THREAD

**Issue by SkySkimmer** [DeepSpec/sf#12]
`git clone` produces a 4.3GB repository.
This seems to be because of the included .tgz (which git doesn't know how to deal with efficiently).

Is this worth trying to avoid? clone --depth 1 produces a 156MB repo which is more reasonable (deleting the tgz makes a depth 1 clone of 93MB).

**Comment by liyishuai** [comment]
If we agree that versioning is unnecessary for this (downstream) repo, then squashing the commits might reduce the cloning size.

**Comment by bcpierce00** [comment]
I don't see any utility in versioning for this repo.
