### ISSUE TITLE
Referenced "UseAuto" chapter does not exist

### ISSUE THREAD

**Issue by jfehrle** [DeepSpec/sf#9]
`V1 Logical Foundations/lf/Auto.v` says "A deeper treatment of [auto] and [eauto] can be found in the [UseAuto] chapter in _Programming Language Foundations_.", but that chapter appears not to exist.

**Comment by bcpierce00** [comment]
Really?  I see it in the sources and in the TOC on the web...

**Comment by jfehrle** [comment]
My mistake. pilot error.  I downloaded the source for the 6 volumes so I could do text searches across all of them at once, but I dropped VFA in place of PLF.

**Comment by bcpierce00** [comment]
Whew.
